pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'scheduler-meetings:$(Build.BuildId)'

steps:
- script: docker build -f UsSchedulerMeetings/Dockerfile -t $(dockerId).azurecr.io/$(imageName) .
  workingDirectory: src/
  displayName: 'Docker Build'

- script: |
    docker login -u $(dockerId) -p $pswd $(dockerId).azurecr.io
    docker push $(dockerId).azurecr.io/$(imageName)
  env:
    pswd: $(dockerPassword)
  workingDirectory: src/
  displayName: 'Docker Push'